# Generated by Django 4.1.4 on 2022-12-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profession',
            options={'verbose_name': 'Профессия', 'verbose_name_plural': 'Профессии'},
        ),
        migrations.AddField(
            model_name='profession',
            name='image',
            field=models.ImageField(default=None, upload_to='images/', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
